### ISSUE TITLE
support for arrow functions (incorrect currently)

### ISSUE THREAD

**Issue by tunnckoCore** [bigpipe/fn.name#1]
currently it works only for arrow functions that don't have arguments/params

``` js
var fnName = require('fn.name')

console.log(fnName(() => 123)) // => anonymous
console.log(fnName(() => {return 123})) // => anonymous
console.log(fnName((a, b, c) => a + b + c)) // => a, b, c
console.log(fnName((a, b) => {return a + b})) // => a, b
```

**Comment by tunnckoCore** [comment]
I can suggest this approach

``` js
function fnName (val) {
  if (typeof val !== 'function') {
    throw new TypeError('fnName expect `val` to be function')
  }
  // regex from `parse-function@2.2.x`
  var re = /(?:function\s*([\w$]*)\s*)*\(*(?:[\w\s,$]*)\)*(?:[\s=>]*)(?:[\s\S]*)/
  return val.displayName || val.name || (re.exec(val) || [])[1] || 'anonymous'
}

console.log(fnName(function () {return 123}))
console.log(fnName(function named () {return 123}))
console.log(fnName(() => 123))
console.log(fnName(() => {return 123}))
console.log(fnName((a, b, c) => a + b + c))
console.log(fnName((a, b) => {return a + b}))
```

the best and guaranteed method would be with `parse-function@2.3` which uses `acorn@3`, but i think it is too much for one name.

**Comment by 3rd-Eden** [comment]
Including a complete parser to just get the name of a function kinda defeats the purpose of having a small module as this.

**Comment by tunnckoCore** [comment]
Agreed. That's why i suggested regex, which in turn would be more faster (i made some benchmarks between different parse-function versions) than using acorn for such thing. :)

**Comment by Swaagie** [comment]
I think @3rd-Eden is saying that anything along the line of parsing out stuff is way beyond what this module is aiming to do. I'd argue that this is a problem with the JS runtime fasely identifying the parameters as `fn.name`. Funny thing is that `fn.arguments` is broken for fat arrow functions as well :)

**Comment by jcrugzz** [comment]
@Swaagie i believe part of the purpose behind `arrow` functions and why they are fast is that they dont create scope, they inherit the scope of the function they are contained within. Because of this they never create an `arguments` object as its `arguments` are also inherited from the parent scope. You have to explicitly list the arguments that you use. It is fascinating to see them end up as part of `fn.name`

**Comment by tunnckoCore** [comment]
Don't go offtopic, please.
I suggested regex - correct, simple, small, fast and doing the job correctly even for es6 arrow functions.

If you want something more robust use `parse-function` (getting correct name, arguments and body of function) it handles everything to ES2016 and handles it correctly.

But here we don't need and not worth using `parse-function` for something so small.

**Comment by jcrugzz** [comment]
@tunnckoCore whats the difference in perf using the regex? I guess thats the biggest blocker from the comments from @Swaagie and @3rd-Eden. I agree that this should be able to work for arrow functions

**Comment by Swaagie** [comment]
Agreed it should work. But afaik `chrome@48.0.2564.109` is already correct. Haven't tested this against other browsers. But until es6 is mainstream in the browser I don't think it makes sense to support untranspiled es6 usage in browsers that will be updated.

```
test = function () { } // "'
test = () => { } // "'
test = (a, b, c) => { } // "'
```

In any of the examples we could simple return `undefined` if the value is falsy.
`arguments` was merely an example of where compilers also use to be erroreous, not off topic. In other works I'm not so convinced we need to support this right now, but happy to be proven wrong.

edit: finally couldn't the regex be simpler to only test against something along the lines of `=>` as we should be able to catch all other examples.

**Comment by tunnckoCore** [comment]
> @jcrugzz: whats the difference in perf using the regex?

between using acorn for parsing and regex – huge (regex is ~40x faster), see benchmarks in `parse-function` repo.

> @Swaagie: finally couldn't the regex be simpler to only test against something along the lines of

Agree. Maybe using `is-arrow-function` package.

**Comment by jcrugzz** [comment]
@tunnckoCore i meant the current perf of this library versus using regex

**Comment by Swaagie** [comment]
This is also working as expected with Chrome (as demonstrated above), Firefox@42.0, Node@4.2.4, Node@5. Both IE11 and Safari doesn't seem to support fat arrows yet. So what is the intended scope of this fix? It seems like we are fixing something that is a side effect of transpilers?

edit: my bad no intention to close this just yet :)

**Comment by tunnckoCore** [comment]
Okey, we will duplicate packages until the end of the world and npm will go with 500k packages soon.

**Comment by tunnckoCore** [comment]
> @Swaagie: ... yet.

Exactly. The scope is that we have arrows support currently in node. Worth nothing to support it.
